import os

data_root = '{}{}'.format(os.path.dirname(os.path.abspath(__file__)), '/../../../dataset')
CONFIG = {
    'train_data_path': f"{data_root}/single_style_pairs/train",
    'eval_path_1': f"{data_root}/(0,20)-FixedPos-oneStyle",
    'eval_path_2': f"{data_root}/single_style_pairs/test",
    'latent_embedding_1': 1,
    'latent_embedding_2': 0,
    'latent_code_2': 0,
    'embedding_dim': 8,
    'embeddings_num': 100,
    'kld_loss_scalar': 0.0,
    'checkpoint_interval': 2000,
    'learning_rate': 1e-4,
    'scheduler_base_num': 0.99999,
    'max_iter_num': 50001,
    'model_path': 'curr_model.pt',
    'train_result_path': 'TrainingResults/',
    'eval_result_path': 'EvalResults/',
    'train_record_path': "Train_record.txt",
    'eval_record_path': "Eval_record.txt",
    'plus_accu_record_path': "plus_eval.txt",
    'log_interval': 200,
    'eval_interval': 2000,
    'is_save_img': True,
    'batch_size': 32,
    'is_commutative_train': False,
    'z_plus_loss_scalar': 0.01,
    'commutative_z_loss_scalar': 0.0,
    'associative_z_loss_scalar': 0.0,
    'plus_recon_loss_scalar': 3,
    'min_loss_scalar': 0.00001,
    'K': 1024,
    'assoc_aug_range': (-3, 3),
    'commitment_scalar': 0.0025,
    'embedding_scalar': 0.01,
    'isVQStyle': False,
    'plus_by_embedding': False,
    'VQPlus_eqLoss_scalar': 0.5,
    'is_zc_based_assoc': True,
    'is_rand_z_assoc': False,
    'is_assoc_on_e': True,
    'is_assoc_on_z': False,
    'network_config': {
        'enc_dec': {
            'img_channel': 3,
            'last_H': 4,
            'last_W': 4,
            'first_ch_num': 16,
        },
        'plus': {
            'plus_unit': 128,
        }
    },
}
