import os

data_root = '{}{}'.format(os.path.dirname(os.path.abspath(__file__)), '/../../../dataset')
CONFIG = {
    'train_data_path': f"{data_root}/multi_style_pairs(0,20)_mahjong/train",
    'single_img_eval_set_path': f"{data_root}/(0,20)-FixedPos-mahjong",
    'plus_eval_set_path': f"{data_root}/multi_style_pairs(0,20)_mahjong/test",
    'plus_eval_set_path_2': None,
    'is_random_split_data': False, # 是否随机划分数据集. 如果为True, 则eval_data_path, plus_eval_set_path_2会被忽略. 数据从train_data_path中随机划分
    'train_data_ratio': 0.8,  # 如果is_random_split_data为True, 则表示从train_data_path中随机划分出多少比例的数据作为训练集
    'is_online_blur': False,
    'latent_embedding_1': 2,
    'latent_embedding_2': 0,
    'multi_num_embeddings': None,
    'latent_code_2': 4,
    'embedding_dim': 1,
    'is_plot_zc_value': False,
    'embeddings_num': 10,
    'is_plot_vis_num': False,
    'kld_loss_scalar': 0.0,
    'checkpoint_interval': 500,
    'learning_rate': 1e-4,
    'scheduler_base_num': 0.99999,
    'max_iter_num': 50001,
    'model_path': 'curr_model.pt',
    'train_result_path': 'TrainingResults/',
    'eval_result_path': 'EvalResults/',
    'train_record_path': "Train_record.txt",
    'eval_record_path': "Eval_record.txt",
    'plus_accu_record_path': "plus_eval.txt",
    'log_interval': 100,
    'eval_interval': 500,
    'is_save_img': True,
    'batch_size': 256,
    'is_commutative_train': False,
    'is_commutative_all': False,
    'z_plus_loss_scalar': 0.02,
    'commutative_z_loss_scalar': 0.0,
    'associative_z_loss_scalar': 0.0,
    'plus_mse_scalar': -1,
    'plus_recon_loss_scalar': 3,
    'min_loss_scalar': 0.00001,
    'K': 1024,
    'assoc_aug_range': (-3, 3),
    'commitment_scalar': 0.0025,
    'embedding_scalar': 0.01,
    'isVQStyle': False,
    'plus_by_embedding': True,
    'plus_by_zcode': False,
    'VQPlus_eqLoss_scalar': 0.5,
    'is_zc_based_assoc': True,
    'is_rand_z_assoc': False,
    'is_assoc_on_e': True,
    'is_assoc_on_z': False,
    'is_assoc_within_batch': False,
    'is_switch_digital': False,
    'is_symm_assoc': False,
    'is_full_symm': False,
    'is_pure_assoc': False,
    'is_twice_oper': False,
    'network_config': {
        'enc_dec': {
            'img_channel': 3,
            'last_H': 4,
            'last_W': 4,
            'first_ch_num': 16,
        },
        'enc_fc': {
            'n_units': 128,
            'n_hidden_layers': 2,
        },
        'plus': {
            'plus_unit': 1024,
            'n_hidden_layers': 2,
        }
    },
    'eval_config': {
        'pipline_result_path': 'PIPLINE_EVAL',
        'plus_eval_config': {
            'eval_set_path_list': [
                f"{data_root}/multi_style_pairs(0,20)_mahjong/test",
            ],
            'one2n_accu_result_name': 'one2n_accu',
            'one2one_accu_result_name': 'one2one_accu',
        }
    },
}
